# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f0e726be8078a6cbe7408a6b85141bfa13ba3082c9a79e09c00f14d1a6eb1f7da8a8ec508c3f38fadb0c58796daa55e56450b707579cdd0aa98e6f1ed76b3c8

test:
  secret_key_base: 4d8ae5d4b093fe03f955b185a3a875716db428bdc606aab2b97e3ae983ead97bf5c8e2b27c02eaa01789a06549290117ae3cfe739dbcb49588aa0eb4a5662e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
